services:
  devops-postgres:
    container_name: devops-postgres
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - devops-network
    ports:
      - 5432:5432
    restart: unless-stopped
  contenedor-devops-api-node:
    container_name: contenedor-devops-api-node
    image: devops-api-node
    build:
      context: ./api-node
      dockerfile: Dockerfile
    init: true
    depends_on:
      - devops-postgres
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@devops-postgres:5432/postgres
    networks:
      - devops-network
    ports:
      - 3000:3000
    restart: unless-stopped
  contenedor-devops-api-golang:
    container_name: contenedor-devops-api-golang
    image: devops-api-golang
    build:
      context: ./api-golang
      dockerfile: Dockerfile
    init: true
    depends_on:
      - devops-postgres
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@devops-postgres:5432/postgres
    networks:
      - devops-network
    ports:
      - 8080:8080
    restart: unless-stopped
  client-react:
    image: devops-client-react
    build:
      context: ./client-react
      dockerfile: Dockerfile
    init: true
    depends_on:
      - contenedor-devops-api-node
      - contenedor-devops-api-golang
    networks:
      - devops-network
    ports:
      - 5173:5173
    restart: unless-stopped
volumes:
  pgdata:
networks:
  devops-network:
